# pyproject.toml
[build-system]
# XXX: If your project needs other packages to build properly, add them to this list.
requires = ["setuptools >= 42.0.0", "numpy = 1"]
build-backend = "setuptools.build_meta"
